name: Deployment
on:
  push:
    branches: [main]
    paths:
      - 'cicd'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
      - name: Run scripts
          run: dploy deploy main
